---
  - name: Configure hosts and deploy applications
    hosts: all
    tasks: 
      - name: Change mongo config file
        become: true
        template: 
          src: templates/mongod.conf.j2
          dest: /etc/mongod.conf
          mode: 0644
    tags: db-tag
