---
  - name: Configure hosts and deploy applications
    hosts: all
    vars:
      mongo_bind_ip: 0.0.0.0
      db_host: 10.132.15.228
    tasks: 
      - name: Change mongo config file
        become: true
        template: 
          src: templates/mongod.conf.j2
          dest: /etc/mongod.conf
          mode: 0644
        tags: db-tag

      - name: Add unit file for puma
        become: true
        copy:
          src: files/puma.service
          dest: /etc/systemd/system/puma.service
        tags: app-tag
        notify: reload puma
    
      - name: Add config for DB connection
        template:
          src: templates/db_config.j2
          dest: /home/dennisananiev/db_config
        tags: app-tags

      
      - name: Fetch the latest version of application code
        git:
          repo: 'https://github.com/express42/reddit.git'
          dest: /home/dennisananiev/reddit
          version: monolith # <-- Указываем нужную ветку
        tags: deploy-tag
        notify: reload puma
      
      - name: Bundle install
        bundler:
          state: present
          chdir: /home/dennisananiev/reddit # <-- В какой директории выполнить команду
        tags: deploy-tag
      
      
      - name: enable puma
        become: true
        systemd: name=puma enabled=yes
        tags: app-tag

    handlers:
      - name: restart mongod
        become: true
        service: name=mongod state=restarted

      - name: reload puma
        become: true
        systemd: name=puma state=restarted
